### ISSUE TITLE
Alert: Didn't find any bluetooth low energy device

### ISSUE THREAD

**Issue by UgurYasarKazdal** [don/ionic-ble#1]
Hi,
I'm new with ionic framework. Install the plugin correctly. So I try to use your example and run on my phone (Samsung Galaxy S5 that has Bluetooth®: 4.0 BLE) 
and try to find other phone (LG G3) but I gave the alert "didn't find any bluetooth low energy device". 
and this warning from logcat:
THREAD WARNING: exec() call to BLE.stopScan blocked the main thread for 33ms. Plugin should use CordovaInterface.getThreadPool().
Thanks.

**Comment by don** [comment]
The S5 will only find your G3 if the G3 is advertising a Bluetooth Low Energy service. Android peripheral support is relatively new. It requires Android 5.0+ and supported BLE chipsets. If you have both you can write an app to advertise a BLE service. Then the S5 will see your phone.

Typically in a place with a lot of people I will see BLE fitness trackers when I scan. I like using [bleno](https://github.com/sandeepmistry/bleno) to create BLE peripherals nodejs on my computer. Try the [echo example](https://github.com/sandeepmistry/bleno/tree/master/examples/echo).

You can use a tool like [nRF Master Control Panel](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) to compare scan results with ionic-ble.

Ignore that thread warning.

**Comment by don** [comment]
@UgurYasarKazdal if you have a Mac or Linux box that supports BLE 4, try creating a BLE peripheral using Node.js and [Bleno](https://github.com/sandeepmistry/bleno). I suggest trying the [echo service](https://github.com/sandeepmistry/bleno/tree/master/examples/echo) to start.
