### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by soumendub3** [don/ionic-ble#2]
@don I downloaded your example and followed the steps you outlined but the example does not find any nearby BLE devices. I verified with nRF Master Control Panel that the devices are active. 
![screenshot_2015-09-16-13-49-27](https://cloud.githubusercontent.com/assets/14145517/9914959/0a8de812-5c7a-11e5-8638-fca010e526ae.png)

When I change to BLE tab, I see no devices - I am assuming looking at the code that the tab controller should initiate a scan when refreshed. Can you see if this is an issue? I think it is not doing an initial scan to find devices so the list never gets populated and then there is nothing to pull down to refresh. All I see is a white blank screen in the BLE tab. 
![screenshot_2015-09-16-13-49-01](https://cloud.githubusercontent.com/assets/14145517/9914987/3cd48ce0-5c7a-11e5-87a2-7072352b4d5c.png)

I am using a Samsung G5 with Ionic View app and I have successfully used your cordova-plugin-ble-central with the same phone and Phonegap. I have commented on Issue#79 earlier yesterday and today. Any help will be greatly appreciated.

**Comment by don** [comment]
@soumendub3 you should see devices when it scans.

This app will **not** work with [Ionic View](http://view.ionic.io/), since the BLE plugin is not installed in that app.
You can use the [PhoneGap Developer App](https://play.google.com/store/apps/details?id=com.adobe.phonegap.app) since my plugin is pre-installed in the app.

Check `adb logcat` and chrome://inspect to make sure there aren't any errors.

![device-2015-09-16-234335](https://cloud.githubusercontent.com/assets/3133/9924399/1cc06bd8-5ccd-11e5-8032-b9a9355fdd46.png)

**Comment by soumendub3** [comment]
@don Yes, that was the issue - I can run flawlessly using PhoneGap. 

Can you tell me if there is a way to add the plugin into the Ionic View? Is this something you can add - with Phonegap, I am tied to having my phone in the same network as my PC so client demo is tough without the PC. Can you help? However, I understand it is out of scope for this topic but may be beneficial if you comment or point to the right place. 

We can close this issue.

**Comment by don** [comment]
Drifty (or Ionic) needs to add the plugin to their app before they deploy it to the apps store.

I worked with the PhoneGap team to get my plugin added to the PhoneGap developer app. Feel free to put in a request with the Ionic / Drifty team about adding the plugin to Ionic View.

**Comment by soumendub3** [comment]
Thank you Don for promptly addressing the issue - I will follow up in the Ionic Forum. Greatly appreciate your help and thank you for the wonderful plugin!!
