### ISSUE TITLE
How can i apply this to bluno board?

### ISSUE THREAD

**Issue by laics1984** [don/ionic-ble#3]
hi there, i have tried to apply ur example to detech a bluno board but it has no response. May i know whether there is any configuration that need to be done? Thanks.

**Comment by don** [comment]
You should be able to discover a Bluno with this example, but unfortunately Bluno's BLE implementation breaks the BLE spec so it doesn't work well with my ble-central plugin or other BLE tools. See http://www.dfrobot.com/forum/viewtopic.php?f=18&t=2035&p=9213&hilit=ble+central#p9213

You can modify the plugin and comment out any code reading or writing 0x2902 to get it to work.
